---
# handlers file for mysql
- name: iniciando o banco
  service: name=mariadb state=started enabled=true

- name: restartando o banco
  service: name=mariadb state=restarted enabled=true
 
- name: iniciando mysql
  service: name=mysql state=started enabled=true
  service: name=mysql state=restarted enabled=true
