Vagrant.configure("2") do |config| #configuração de valores globais memoria e cpu
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 2 
    end

    config.vm.define "wordpress" do |wordpress|
        wordpress.vm.provider "virtualbox" do |v|
        wordpress.vm.network "private_network", ip: "172.13.0.22", bridge: "wlp1s0"
        wordpress.vm.hostname = "wordpress"
        v.name = "wordpress"
        v.memory = 512
        v.cpus = 1
    end
  end
end
