---
  - hosts: wordpress
    handlers:
      - name: restart apache
        service:
          name: apache2
          state: restarted
        become: yes

    tasks:
      - name: 'Instala pacotes de dependencia do sistema operacional'
        apt:
          name:
          - python2.7
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - libssh2-php
          - php5-mcrypt
          - php5-mysql
          state: latest
        become: yes
       
      - name: 'Baixa o arquivo de instalação do Wordpress'
        get_url:
          url: 'https://br.wordpress.org/wordpress-5.1.4-pt_BR.tar.gz'
          dest: '/tmp/wordpress-5.1.4-pt_BR.tar.gz'

      - name: 'Descompactar o arquivo wordpress'
        unarchive:
          src: '/tmp/wordpress-5.1.4-pt_BR.tar.gz'
          dest: /var/www/
          remote_src: yes
        become: yes  

      - name: 'Copiando e modificando arquivo de instalação'
        copy: 
          src: '/var/www/wordpress/wp-config-sample.php'
          dest: '/var/www/wordpress/wp-config.php'
          remote_src: yes
        become: yes  
    
      
      - name: 'Configura o wp-config com as entradas do banco de dados' 
        replace:
          path: '/var/www/wordpress/wp-config.php'
          regexp: "{{ item.regex }}"
          replace: "{{ item.value }}"
        loop:
          - { regex: 'nome_do_banco_de_dados_aqui', value: 'wordpress_db' }
          - { regex: 'nome_de_usuario_aqui', value: 'wordpress_user' }
          - { regex: 'senha_aqui', value: '1234' }
          - { regex: 'localhost', value: '192.168.99.23' }
        become: yes

      - name: 'Configura Apache para servir o Wordpress'
        copy:
          src: 'files/000-default.conf'
          dest: '/etc/apache2/sites-available/000-default.conf'
        become: yes
        notify:
          - restart apache

