Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
    end

    #WORDPRESS

    config.vm.define "wordpress" do |wordpress|
    	wordpress.vm.hostname = "wordpress"
        wordpress.vm.network "private_network", ip: "192.168.99.22", dns: "8.8.8.8"
        wordpress.vm.box = "ubuntu/trusty64"
        wordpress.vm.synced_folder "./configs", "/configs" #diretório compartilhado
        wordpress.vm.synced_folder ".", "/vagrant", disabled: true
        wordpress.vm.provision "shell", inline: "cat /configs/myid_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
        wordpress.vm.provision "shell", inline: "cat /configs/myid_rsa.pub /root/.ssh/authorized_keys"
        wordpress.vm.provision "shell", inline: "cp /configs/myid_rsa.pub /root/.ssh/authorized_keys"
        wordpress.vm.provision "shell", inline: <<-SHELL
    apt update -y
  SHELL

  config.vm.provider "virtualbox" do |wordpress|
  	wordpress.memory = "512"
end
end
end

