Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
    
end

    #WORDPRESS

    config.vm.define "wordpress" do |wordpress|
    	wordpress.vm.hostname = "wordpress"
        wordpress.vm.network "private_network", ip: "192.168.99.22", dns: "8.8.8.8"
        wordpress.vm.box = "ubuntu/trusty64"
        wordpress.vm.synced_folder "./configs", "/configs" #diretório compartilhado
        wordpress.vm.synced_folder ".", "/vagrant", disabled: true
        wordpress.vm.provision "shell", inline: "cat /configs/myid_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
        wordpress.vm.provision "shell", inline: "cat /configs/myid_rsa.pub /root/.ssh/authorized_keys"
        wordpress.vm.provision "shell", inline: "cp /configs/myid_rsa.pub /root/.ssh/authorized_keys"
        wordpress.vm.provision "shell", inline: <<-SHELL
    apt update -y
  SHELL
        wordpress.vm.provision "shell", inline: <<-SHELL
    apt upgrade -y
  SHELL
  config.vm.provider "virtualbox" do |wordpress|
  	wordpress.memory = "512"
end
end

 #MYSQL

    config.vm.define "mysql" do |mysql|
        mysql.vm.hostname = "mysql"
        mysql.vm.network "private_network", ip: "192.168.99.23", dns: "8.8.8.8"
        mysql.vm.box = "ubuntu/bionic64"
        mysql.vm.synced_folder "./configs", "/configs" #diretório compartilhado
        mysql.vm.synced_folder ".", "/vagrant", disabled: true
        mysql.vm.provision "shell", inline: "cat /configs/myid_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
        mysql.vm.provision "shell", inline: "cat /configs/myid_rsa.pub /root/.ssh/authorized_keys"
        mysql.vm.provision "shell", inline: "cp /configs/myid_rsa.pub /root/.ssh/authorized_keys"
        mysql.vm.provision "shell", inline: <<-SHELL
    apt install pip
        mysql.vm.provision "shell", inline: <<-SHELL
    apt update -y
  SHELL
        mysql.vm.provision "shell", inline: <<-SHELL
    apt upgrade -y
  SHELL

  config.vm.provider "virtualbox" do |mysql|
    mysql.memory = "1024"

   end
  end
end

