---
# defaults file for mysql

mariadb_users: []
password_root_banco: ''
mariadb_database: []
bind_address: '0.0.0.0'
log_error: /var/log/mariadb/log
pid_file: /var/run/mariadb/mariadb.pid
socket_path: /var/lib/mysql/mysql.sock
datadir: /var/lib/mysql
