$script_mysql = <<-SCRIPT
apt-get update && apt-get install -y mysql-server-5.7 && \
mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "mysqldb" do |mysql|
    mysql.vm.network "public_network", ip: "192.168.0.101", bridge: "wlp1s0"

    mysql.vm.provision "shell", inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
    mysql.vm.provision "shell", inline: "echo Hello, World >> hello.txt"
    mysql.vm.provision "shell", inline: $script_mysql
    mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    mysql.vm.provision "shell", inline: "service mysql restart"

    mysql.vm.synced_folder "./configs", "/configs"
    mysql.vm.synced_folder ".", "/vagrant", disabled: true
  end


  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.network "public_network", ip: "192.168.0.102", bridge: "wlp1s0"
    phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    phpweb.vm.provision "shell", inline: "apt-get update && apt-get install -y puppet"
    phpweb.vm.provision "shell", inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"

        phpweb.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "./configs/manifests"
        puppet.manifest_file = "phpweb.pp"

  end
  end

  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network", ip: "192.168.0.103", bridge: "wlp1s0"
    mysqlserver.vm.provision "shell", inline: "cat /configs/vagrant.pub >> .ssh/authorized_keys"
    mysqlserver.vm.synced_folder "./configs", "/configs"
    mysqlserver.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.0.104", bridge: "wlp1s0"
    ansible.vm.hostname "ansible-machine"
    ansible.vm.provision "shell", inline: "cat /configs/havana.pub >> .ssh/authorized_keys"
    ansible.vm.provision "shell",
    inline: "apt-get update && \
             apt-get install -y software-properties-common && \
             apt-add-repository --yes --update ppa:ansible/ansible && \
             apt-get update
             apt-get install -y ansible"
    ansible.vm.synced_folder "./configs", "/configs"
    ansible.vm.synced_folder ".", "/vagrant", disabled: true
  end
 end
