---

- name: deploy da aplicação com o uso do modulo docker
  docker_container:
    name: wordpress-app
    image: "wordpress:{{ version_app }}"
    restart: yes
    ports:
      - "8080:80"
    env:
      - WORDPRESS_DB_HOST=192.168.99.12
      - WORDPRESS_DB_USER=wordpress_user
      - WORDPRESS_DB_PASSWORD=443322
